Revert "Add architecture dependency on ruby-libs to ruby-irb."
This reverts commit d3938ffb0a8cf3e4917fd8a2ad8e491791ff23d0, since it
produces build error:

BuildError: mismatch when analyzing
ruby-irb-2.0.0.0-0.1.r39357.fc19.noarch.rpm, rpmdiff output was:
removed     REQUIRES ruby-libs(x86-64) = 2.0.0.0
added       REQUIRES ruby-libs(x86-32) = 2.0.0.0